### ISSUE TITLE
Does this work on a public domain or limited to local dev environment ?

### ISSUE THREAD

**Issue by TheLionDevelopment** [ShinoKana/multipleWindow3dScene#1]
I was wondering if this also works when not running locally ?

**Comment by twsh0305** [comment]
就是基础的html和JavaScript，有浏览器就能运行
It is the foundation HTML and JavaScript, which can run with a browser

**Comment by ShinoKana** [comment]
Yep, it can work on a public domain, but just remember that it relies on localStorage which means all windows need to be on the same domain for it to sync up properly. Works great for local dev, and should be fine on a public domain as long as it sticks to that rule.
